@startuml

interface AnnotationConfigRegistry{
void register(Class<?>... annotatedClasses)
void scan(String... basePackages)
}
AnnotationConfigRegistry <|.. AnnotationConfigApplicationContext

@enduml