@startuml

interface BeanPostProcessor{
Object postProcessBeforeInitialization(Object bean, String beanName)
Object postProcessAfterInitialization(Object bean, String beanName)
}
interface InstantiationAwareBeanPostProcessor
interface DestructionAwareBeanPostProcessor
interface MergedBeanDefinitionPostProcessor

BeanPostProcessor <|-- InstantiationAwareBeanPostProcessor
BeanPostProcessor <|-- DestructionAwareBeanPostProcessor
BeanPostProcessor <|-- MergedBeanDefinitionPostProcessor

@enduml