@startuml

interface BeanFactoryPostProcessor
interface BeanDefinitionRegistryPostProcessor

BeanFactoryPostProcessor <|-- BeanDefinitionRegistryPostProcessor
BeanFactoryPostProcessor <|.right. EventListenerMethodProcessor
BeanDefinitionRegistryPostProcessor <|.right. ConfigurationClassPostProcessor

@enduml