@startuml

interface AliasRegistry
interface BeanDefinitionRegistry

AliasRegistry <|-down- BeanDefinitionRegistry

AliasRegistry <-up- SimpleAliasRegistry
BeanDefinitionRegistry <-up- SimpleBeanDefinitionRegistry
SimpleAliasRegistry <|-down- SimpleBeanDefinitionRegistry
BeanDefinitionRegistry <|-down- DefaultListableBeanFactory
SimpleAliasRegistry <|-down- DefaultListableBeanFactory

@enduml