@startuml

BeanFactory --> AbstractBeanFactory: getBean
AbstractBeanFactory --> AbstractBeanFactory: doGetBean
AbstractBeanFactory --> AbstractAutowireCapableBeanFactory: createBean
AbstractAutowireCapableBeanFactory --> AbstractAutowireCapableBeanFactory: doCreateBean
AbstractAutowireCapableBeanFactory --> AbstractAutowireCapableBeanFactory: initializeBean

@enduml