@startuml
interface Callback
interface Dispatcher
interface LazyLoader
interface MethodInterceptor
interface Noop
interface InvocationHandler
interface FixedValue
interface ProxyRefDispatcher

Callback <|-- Dispatcher
Callback <|-- LazyLoader
Callback <|-- MethodInterceptor
Callback <|-- Noop
Callback <|-- InvocationHandler
Callback <|-- FixedValue
Callback <|-- ProxyRefDispatcher

@enduml