# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站信息
## 网站标题
title: holmofy
## 子标题
subtitle:
description: 胡飞飞的个人博客
keywords:
  - Java
  - DB
  - Alibaba
  - Holmofy
  - 胡飞飞
author: 胡飞飞
language: zh-Hans
timezone: Asia/Shanghai
email: 1938304905@qq.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
## 如果你的网站存放在子目录中,比如http://yoursite.com/child,那么你需要将root配置为'/child/'
url: https://blog.hufeifei.cn
root: /
permalink: :year/:month/:title/
permalink_defaults:
# Directory

## 博客markdown源文件夹
source_dir: source
## 站点目录文件夹
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - google4b244692104f4e5f.html
  - baidu_verify_code-4FNAayJ9H3.html
  - ads.txt
  - root.txt
  - robots.txt
  - webpushr-sw.js
  - book/index.html

# 写作选项 Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # 新标签页中打开外链
  field: site
  exclude: 
    - www.hufeifei.cn
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: paper
meta_generator: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
## 这里使用git部署网站
deploy:
  type: git
  repo: git@blog.hufeifei.cn:repo/blog.hufeifei.cn.git
  branch: master
  message: "hexo deployment: {{ now('YYYY-MM-DD HH:mm:ss') }}"

# https://github.com/hexojs/hexo-generator-index
index_generator:
  path: ""
  per_page: 10
  order_by: -date
# https://github.com/hexojs/hexo-generator-archive
archive_generator:
  per_page: 50
  yearly: true
  monthly: false
  daily: false
  order_by: -date
# https://github.com/wzpan/hexo-generator-search
# search:
#   path: search.json
#   field: post
#   content: true

#插件配置
# https://github.com/hexojs/hexo/wiki/Plugins
plugins:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap
  - hexo-filter-mathjax
  - hexo-excerpt
  - hexo-filter-nofollow
  - hexo-filter-plantuml
  - hexo-admin
  - hexo-toc
  - hexo-reference

# https://github.com/hexojs/hexo-renderer-marked
marked:
  # 图片绝对路径
  prependRoot: true
  postAsset: true
  # 用hexo-toc替换
  headerIds: false
  anchorAlias: false
  # 用hexo-filter-nofollow替换
  external_link: 
    enable: false

# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom ##feed类型 atom或者rss2
  path: atom.xml ##feed路径
  limit: 20 ##feed文章最小数量

# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml
  rel: true
baidusitemap:
  path: baidusitemap.xml
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

# 配置Math.js
mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: false # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter

# https://github.com/chekun/hexo-excerpt
excerpt:
  depth: 3
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

# https://github.com/hexojs/hexo-filter-nofollow
# 解决图片外链的问题
nofollow:
  enable: true
  elements: ["a", "img"]
  field: post
  include:
    - "img-blog.csdn.net"
    - "*.sinaimg.cn"
    - "*.doubanio.com"
    - "duanple.com"
  rel:
    - 'external'
    - 'noreferrer'
    - 'nofollow'
    - 'noopener'
  referrerpolicy: 'no-referrer'

# https://github.com/miao1007/hexo-filter-plantuml
# 添加plantuml的支持
plantuml:
  #  Local or PlantUMLServer.
  render: "PlantUMLServer"
  # The render server, you can also create your self-hosting sever
  # self-hosting cmd: java -jar /usr/local/Cellar/plantuml/1.2021.5/libexec/plantuml.jar -picoweb
  # server: http://localhost:8080/plantuml
  server: "http://www.plantuml.com/plantuml"
  # "inline": <svg>xxx<svg/>
  # "inlineUrlEncode": <img src='data:image/svg+xml;> 
  # "inlineBase64": <img src='data:image/svg+xml;base64> 
  # "localLink": <img src="/assert/puml/xxxx.svg">
  # "externalLink": <img src="http://www.plantuml.com/plantuml/svg/xxx">
  link: "inlineBase64"

  # common options: svg/png
  outputFormat: "svg"

# https://github.com/jaredly/hexo-admin
admin:
  username: holmofy
  password_hash: $2a$10$7pJS5p7CijNIU9YRx3X3/O7xPmrU8Cn12c9OwwTWsVP/zVs.ZtuAq
  secret: 4766cFmSgcpF3bXwVlYRxwXdWCx6kFAa6GvPD4KDccU3GLRDAXuqqPx5o5UB8pu2J84+KNT4GaXOTog3l2RmrA==
  deployCommand: "./hexo-deploy.sh"

# https://github.com/bubkoo/hexo-toc
toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
   position: before
   symbol: '#'
   style: header-anchor
  #anchor: false

# https://github.com/hexojs/hexo-asset-pipeline
asset_pipeline:
  revisioning:
    enable: false
  clean_css:
    enable: true
  uglify_js:
    enable: true
  imagemin:
    enable: false
  html_minifier:
    # 有bug
    enable: true
    ignore_error: false
    removeComments: true
    collapseWhitespace: true
    minifyJS: true
    minifyCSS: true

# https://github.com/glazec/hexo-web-push-notification
webPushNotification:
  webpushrKey: "df5d99e7437d3ed74084a178d285cebf"
  webpushrAuthToken: "39510"
  trackingCode: "BPJzNs1QEtbYa3Bn0gMAQHBAzX3Jm71llGUKHTkKEUs3D9xiDYZ0DWJ3S9sfCAAJHxXEoBkUANFyONjeIlgrJUo'"
