@startuml

interface Advised
Advised <|.. AdvisedSupport
AdvisedSupport <|.. ProxyCreatorSupport
ProxyCreatorSupport <|.. ProxyFactoryBean
ProxyCreatorSupport <|.. ProxyFactory
ProxyCreatorSupport <|.. AspectJProxyFactory

@enduml