@startuml

interface Reader
Reader <|-- ReconcilingBinlogReader
ChainedReader --|> Reader
abstract AbstractReader
Reader <|-- AbstractReader
Reader <|-right- BlockingReader
BlockingReader <|-right- TimedBlockingReader
AbstractReader <|-- BinlogReader
AbstractReader <|-- SnapshotReader
Reader <|-- ParallelSnapshotReader

@enduml